
services:
  app:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: true
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_SESSION: 1
      # Configuración sin Redis
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - app_code:/var/www/html
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      - ~/.composer:/home/www-data/.composer
    ports:
      - "9003:9003"  # Xdebug port
    command: >
      sh -c "
        echo 'Configuring Git safe directory...' &&
        git config --global --add safe.directory /var/www/html &&
        if [ ! -d vendor ] || [ ! -f vendor/autoload.php ]; then
          echo 'Installing Composer dependencies...'
          cd /var/www/html && composer install --no-interaction --prefer-dist
        fi &&
        if [ ! -f /var/www/html/.env ]; then
          echo 'Creating .env file...'
          cd /var/www/html && cp .env.example .env && php artisan key:generate
        fi &&
        echo 'Fixing permissions...' &&
        chown -R www-data:www-data /var/www/html &&
        chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
        echo 'Starting PHP-FPM...' &&
        php-fpm -F
      "
    depends_on:
      - postgres

  nginx:
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - app_code:/var/www/html
      - ./docker/nginx/sites/default.conf:/etc/nginx/sites-enabled/default:ro
    depends_on:
      - app

  postgres:
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: dgsuc_app
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  app_code:
    driver: local
  postgres_data_dev:
    driver: local