# Docker Compose override for local development
# This file handles environment-specific bind mount configurations
services:
  app:
    volumes:
      # Mount Laravel app directly as root
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
      - ./app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      
  nginx:
    volumes:
      # Mount Laravel app directly for nginx
      - ./app:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/sites-available:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - nginx_logs:/var/log/nginx
      
  workers:
    volumes:
      # Mount Laravel app directly for workers
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
      - ./app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      
  scheduler:
    volumes:
      # Mount Laravel app directly for scheduler  
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
      - ./app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache