# Docker Compose override for WSL/Windows
# Use this file when running from WSL: docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.wsl.yml up -d

services:
  app:
    volumes:
      # WSL-specific absolute paths
      - /mnt/d/dgsuc-docker/app:/var/www/html
      - /mnt/d/dgsuc-docker/app/storage:/var/www/html/storage
      - /mnt/d/dgsuc-docker/app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      
  nginx:
    volumes:
      # WSL-specific absolute paths for nginx
      - /mnt/d/dgsuc-docker/app:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/sites-available:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - nginx_logs:/var/log/nginx
      
  workers:
    volumes:
      # WSL-specific absolute paths for workers
      - /mnt/d/dgsuc-docker/app:/var/www/html
      - /mnt/d/dgsuc-docker/app/storage:/var/www/html/storage
      - /mnt/d/dgsuc-docker/app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      
  scheduler:
    volumes:
      # WSL-specific absolute paths for scheduler
      - /mnt/d/dgsuc-docker/app:/var/www/html
      - /mnt/d/dgsuc-docker/app/storage:/var/www/html/storage
      - /mnt/d/dgsuc-docker/app/bootstrap/cache:/var/www/html/bootstrap/cache
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache