
services:
  app:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: true
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_SESSION: 1
      # Configuración sin Redis
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - app_code:/var/www/html
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      - ~/.composer:/home/dgsuc_user/.composer
    ports:
      - "8080:8000"  # Puerto directo de Laravel serve
      - "9003:9003"  # Xdebug port
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  postgres:
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: dgsuc_app
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  app_code:
    driver: local
  postgres_data_dev:
    driver: local