
services:
  app:
    build:
      target: development
    environment:
      APP_ENV: local
      APP_DEBUG: true
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_SESSION: 1
      # Configuración sin Redis
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      # Solo volúmenes Docker - no bind mounts de Windows
      - app_code:/var/www/html
      - php_sessions:/var/www/html/storage/framework/sessions
      - php_cache:/var/www/html/storage/framework/cache
      - composer_cache:/home/www-data/.composer
    ports:
      - "9003:9003"  # Xdebug port
    command: >
      sh -c "
        echo 'Configuring Git safe directory...' &&
        git config --global --add safe.directory /var/www/html &&
        echo 'Checking if Laravel app exists...' &&
        if [ -f /var/www/html/composer.json ]; then
          echo 'Laravel app found, setting up environment...' &&
          if [ ! -f /var/www/html/.env ] && [ -f /var/www/html/.env.example ]; then
            echo 'Creating .env file from .env.example...' &&
            cd /var/www/html && cp .env.example .env && php artisan key:generate
          fi &&
          echo 'Fixing permissions...' &&
          chown -R www-data:www-data /var/www/html &&
          chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
        else
          echo 'Laravel app not found. Please clone the repository manually:' &&
          echo '  1. docker exec -it dgsuc_app bash' &&
          echo '  2. git clone https://github.com/cristianfloyd/dgsuc-app.git /tmp/app' &&
          echo '  3. mv /tmp/app/* /var/www/html/ && mv /tmp/app/.* /var/www/html/ 2>/dev/null || true' &&
          echo '  4. composer install' &&
          echo 'Container will keep running for manual setup...'
        fi &&
        echo 'Starting PHP-FPM...' &&
        php-fpm -F
      "
    depends_on:
      - postgres

  nginx:
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      # Solo volúmenes Docker - no bind mounts de Windows
      - app_code:/var/www/html:ro
      - nginx_config:/etc/nginx/sites-enabled:ro
    depends_on:
      - app

  postgres:
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: dgsuc_app
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql/01-create-schema.sql:/docker-entrypoint-initdb.d/01-create-schema.sql:ro

volumes:
  app_code:
    driver: local
  postgres_data_dev:
    driver: local
  composer_cache:
    driver: local
  nginx_config:
    driver: local